# Generated by Django 2.2.28 on 2023-03-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsr', '0004_auto_20230319_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': [('manage_shops', 'Can create and edit shops')]},
        ),
    ]
