# Generated by Django 2.2.28 on 2023-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsr', '0005_auto_20230319_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
