# Generated by Django 2.2.28 on 2023-03-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsr', '0005_auto_20230319_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
