# Generated by Django 2.2.28 on 2023-03-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsr', '0006_auto_20230321_0051'),
        ('gsr', '0006_category_is_approved'),
    ]

    operations = [
    ]
