# Generated by Django 2.2.28 on 2023-03-22 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsr', '0007_merge_20230321_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerGroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(null=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('request_comment', models.TextField(max_length=2048)),
                ('evidence_file', models.FileField(upload_to='owner_evidence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
