# Generated by Django 2.2.28 on 2023-03-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsr', '0009_ownergrouprequest_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='views',
        ),
    ]
